<script lang="ts">
	import { base } from '$app/paths';
	import Architecture from '$lib/components/Architecture.svelte';

	const internals = [
		{
			tag: 'the client',
			title: 'Generated, then pinned',
			body: 'The typed client is generated by openapi-typescript from a committed snapshot of the supervisor’s /openapi.json. The snapshot pins the contract version the client was built against; at runtime checkApiCompatibility compares it to GET /health and warns on drift. The supervisor is a moving dev build, so the check informs rather than blocks.',
			code: ['npm run generate      # from the committed snapshot', 'npm run generate:live  # refresh, then generate']
		},
		{
			tag: 'staying live',
			title: 'Discovery and resilience',
			body: 'The extension finds the supervisor through an explicit setting, a discovery descriptor, or the localhost default, probes /health, and keeps a status-bar indicator live across gc stop and supervisor restarts with exponential-backoff reconnect. SSE streams reconnect chunk-safe. The core imports no vscode and runs in plain Node.',
			code: ['discovery → /health probe → ready', 'restart → backoff → re-discover → resubscribe']
		},
		{
			tag: 'proof',
			title: 'Three testing seams',
			body: 'Seam 1 is the vscode-free core: the typed client and the resilience state machine, exercised against an injected mock fetch and an OpenAPI-conformant mock /v0. That is where most behavior is proven. Seam 2 is the webview to extension-host postMessage protocol. Seam 3 is a thin set of live-contract checks against a real supervisor.',
			code: ['vitest run            # seam 1, headless', '416 tests green']
		}
	];
	const repo = 'https://github.com/jsgerman-oss/gascity-cockpit';
</script>

<svelte:head>
	<title>Architecture · GasCity Cockpit</title>
	<meta name="description" content="How GasCity Cockpit works: a pure client of the gascity /v0 API, a feature-registry host, a generated and version-pinned typed client, and three testing seams." />
</svelte:head>

<Architecture />

<section class="section internals">
	<div class="shell">
		<header class="sec-head">
			<p class="eyebrow">Internals</p>
			<h2 class="sec-title">No magic, just seams.</h2>
		</header>
		<div class="rows">
			{#each internals as it}
				<article class="row">
					<div class="row-l">
						<span class="row-tag">{it.tag}</span>
						<h3 class="row-title">{it.title}</h3>
					</div>
					<div class="row-r">
						<p class="row-body">{it.body}</p>
						<pre class="snip">{#each it.code as line}<code>{line}</code>{/each}</pre>
					</div>
				</article>
			{/each}
		</div>
		<a class="btn-ghost" href={repo} target="_blank" rel="noreferrer">Read the source</a>
	</div>
</section>

<style>
	.section {
		padding-block: clamp(3.5rem, 8vw, 6.5rem);
	}
	.sec-head {
		margin-bottom: clamp(2.5rem, 5vw, 3.5rem);
	}
	.sec-title {
		font-size: var(--text-title);
		margin-top: 0.9rem;
	}
	.rows {
		border-top: 1px solid var(--hairline);
	}
	.row {
		display: grid;
		grid-template-columns: minmax(0, 0.8fr) minmax(0, 1.6fr);
		gap: clamp(1.5rem, 4vw, 4rem);
		padding-block: clamp(2rem, 4vw, 2.75rem);
		border-bottom: 1px solid var(--hairline);
	}
	.row-tag {
		font-family: var(--font-mono);
		font-size: 0.6875rem;
		letter-spacing: 0.14em;
		text-transform: uppercase;
		color: var(--accent);
	}
	.row-title {
		font-size: 1.375rem;
		font-weight: 600;
		color: var(--ink);
		margin-top: 0.6rem;
		letter-spacing: -0.015em;
	}
	.row-body {
		font-size: 0.9375rem;
		line-height: 1.6;
		color: var(--mute);
		max-width: 58ch;
	}
	.snip {
		margin-top: 1.25rem;
		padding: 1rem 1.1rem;
		background: var(--surface);
		border: 1px solid var(--hairline);
		border-radius: var(--radius-code);
		overflow-x: auto;
	}
	.snip code {
		display: block;
		font-family: var(--font-mono);
		font-size: 0.8125rem;
		line-height: 1.7;
		color: var(--mute);
		white-space: pre;
	}
	.btn-ghost {
		display: inline-flex;
		align-items: center;
		margin-top: clamp(2rem, 4vw, 3rem);
		padding: 0.85rem 1.4rem;
		border: 1px solid var(--hairline-strong);
		color: var(--ink);
		font-weight: 500;
		font-size: 0.9375rem;
		transition: border-color 140ms ease, background 140ms ease, transform 140ms ease;
	}
	.btn-ghost:hover {
		border-color: var(--accent);
		background: var(--lifted);
		transform: translateY(-1px);
	}
	@media (max-width: 720px) {
		.row {
			grid-template-columns: 1fr;
			gap: 1rem;
		}
	}
</style>
