#!/usr/bin/env node
// Generates the typed /v0 client artifacts from the OpenAPI spec.
//
// The committed snapshot at openapi/openapi.json is the single source of truth and
// pins the API contract version the client is built against (PRD: Implementation
// Decisions — "Generate a typed TypeScript client from the live /openapi.json …
// This … pins the API version").
//
//   node scripts/generate-client.mjs           # generate from the committed snapshot
//   node scripts/generate-client.mjs --live    # refresh the snapshot from a running
//                                              # supervisor first, then generate
//
// Outputs:
//   src/api/generated/v0.d.ts     — request/response types (openapi-typescript)
//   src/api/generated/spec-meta.ts — pinned info.version / info.title, derived from the spec
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const snapshotPath = resolve(root, "openapi/openapi.json");
const typesPath = resolve(root, "src/api/generated/v0.d.ts");
const metaPath = resolve(root, "src/api/generated/spec-meta.ts");

const live = process.argv.includes("--live");

if (live) {
  const apiUrl = process.env.GASCITY_API_URL ?? "http://127.0.0.1:8372";
  const specUrl = new URL("/openapi.json", apiUrl);
  console.log(`[generate] fetching live spec from ${specUrl}`);
  const res = await fetch(specUrl);
  if (!res.ok) {
    throw new Error(`failed to fetch ${specUrl}: HTTP ${res.status}`);
  }
  const spec = await res.json();
  // Pretty-print with a trailing newline so diffs of the snapshot stay readable.
  writeFileSync(snapshotPath, JSON.stringify(spec, null, 2) + "\n");
  console.log(`[generate] wrote snapshot ${snapshotPath}`);
}

const spec = JSON.parse(readFileSync(snapshotPath, "utf8"));
const version = spec?.info?.version ?? "unknown";
const title = spec?.info?.title ?? "unknown";

console.log(`[generate] spec: ${title} v${version}`);

// 1. Types from the spec.
const ast = await openapiTS(pathToFileURL(snapshotPath));
const types = astToString(ast);
writeFileSync(
  typesPath,
  `// AUTO-GENERATED by scripts/generate-client.mjs from openapi/openapi.json — DO NOT EDIT.\n` +
    `// Regenerate with: npm run generate\n` +
    types,
);
console.log(`[generate] wrote ${typesPath}`);

// 2. Pinned spec metadata, derived from the same source of truth.
const meta =
  `// AUTO-GENERATED by scripts/generate-client.mjs from openapi/openapi.json — DO NOT EDIT.\n` +
  `// Regenerate with: npm run generate\n` +
  `\n` +
  `/** OpenAPI \`info.title\` the client was generated against. */\n` +
  `export const PINNED_API_TITLE = ${JSON.stringify(title)};\n` +
  `\n` +
  `/** OpenAPI \`info.version\` the client was generated against — the pinned /v0 contract version. */\n` +
  `export const PINNED_API_VERSION = ${JSON.stringify(version)};\n`;
writeFileSync(metaPath, meta);
console.log(`[generate] wrote ${metaPath}`);

console.log("[generate] done.");
