/**
 * Public surface of the Ghostex foundation: the `vscode`-free cores the
 * Ghostex feature (and later beads/session features) are written against.
 * Everything here is unit-tested in plain Node — no `vscode`, no live gxserver.
 */

export {
  DEFAULT_GXSERVER_BASE_URL,
  DEFAULT_TOKEN_PATH,
  GXSERVER_PRODUCT,
  GXSERVER_PROTOCOL_VERSION,
  type GhostexBoardItem,
  type GhostexGlobalSessionRef,
  type GhostexHealth,
  type GhostexLifecycleState,
  type GhostexPresentationGroup,
  type GhostexPresentationProject,
  type GhostexPresentationSession,
  type GhostexPresentationSnapshot,
  type GhostexProject,
  type GhostexProjectId,
  type GhostexRpcError,
  type GhostexRpcSuccess,
  type GhostexServerHealth,
  type GhostexServerId,
  type GhostexSession,
  type GhostexSessionActivity,
  type GhostexSessionId,
  type GhostexSessionKind,
  type GhostexSessionLifecycleResult,
  type GhostexSessionSurface,
  type GhostexTypedOperationResult,
  type GhostexWorktreeEntry,
} from './types.ts';

export {
  GhostexParseError,
  isRecord,
  parseBoardItems,
  parseHealth,
  parseJson,
  parseLifecycleResult,
  parsePresentationSession,
  parsePresentationSnapshot,
  parseProject,
  parseProjectList,
  parseServerHealth,
  parseSession,
  parseSessionList,
  parseSessionText,
  parseTypedOperationResult,
} from './parse.ts';

export {
  CliTransport,
  cliArgsFor,
  GxClient,
  GxClientError,
  RpcTransport,
  type CliTransportOptions,
  type ExecFileLike,
  type FetchLike,
  type GxEndpoint,
  type GxErrorCode,
  type GxParams,
  type GxTransport,
  type RpcTransportOptions,
} from './gxClient.ts';

export {
  discoverGhostex,
  GhostexProbeError,
  probeGhostexHealth,
  probeGhostexServerHealth,
  readiness,
  type GhostexDiscovery,
  type GhostexDiscoveryInputs,
  type GhostexEndpoint,
  type GhostexReadiness,
  type GhostexUnavailableReason,
  type Logger as GhostexLogger,
  type ReadTokenFile,
} from './discovery.ts';

export {
  backoffDelay,
  eventsUrl,
  GhostexEventStream,
  parseGhostexEvent,
  type GhostexDelta,
  type GhostexEvent,
  type GhostexEventStreamOptions,
  type GhostexStreamState,
  type WebSocketFactory,
  type WebSocketLike,
} from './events.ts';

export {
  computeSessionPresentation,
  GhostexExplorerModel,
  resolveGhostexNotice,
  sessionIcon,
  sessionKindLabel,
  type GhostexConnState,
  type GhostexMessageNode,
  type GhostexProjectNode,
  type GhostexSessionNode,
  type GhostexTreeNode,
  type SessionPresentation,
} from './explorerModel.ts';

export {
  applyPlan,
  DEFAULT_CONFLICT_POLICY,
  DEFAULT_LINK_KEYS,
  defaultBoardStatusMapping,
  formatReport,
  planReconcile,
  reconcile,
  type AppliedAction,
  type ApplyResult,
  type BeadCreateInput,
  type BeadPatch,
  type BeadsSide,
  type BoardItemCreateInput,
  type BoardItemPatch,
  type BoardSide,
  type BoardStatusMapping,
  type ConflictPolicy,
  type CreateBeadAction,
  type CreateBoardAction,
  type FieldAuthority,
  type LinkKeys,
  type ReconcileAction,
  type ReconcileError,
  type ReconcileField,
  type ReconcileOptions,
  type ReconcilePlan,
  type ReconcileReport,
  type ReconcileSummary,
  type SyncSide,
  type UpdateBeadAction,
  type UpdateBoardAction,
} from './boardSync.ts';

// The state-sync (agents bridge) surface shares two names with boardSync —
// `reconcile` and `DEFAULT_LINK_KEYS` — but they are different operations over
// different data (session activity/lifecycle vs. bead⇄board items). boardSync's
// names are already the public barrel surface, so the state-sync variants are
// re-exported under disambiguated aliases. Direct importers of './stateSync.ts'
// keep the original names.
export {
  correlateFleetAndGhostex,
  DEFAULT_CWD_KEYS,
  DEFAULT_LINK_KEYS as DEFAULT_SESSION_LINK_KEYS,
  DEFAULT_RECONCILE_POLICY,
  detectCompletion,
  gascityActivityToGhostex,
  gascityFleetToGhostex,
  gascityLifecycleToGhostex,
  gascitySessionCwd,
  gascitySessionLink,
  ghostexActivityToGascity,
  ghostexLifecycleToGascity,
  ghostexSessionToFleetActivity,
  isAgentCompleted,
  normalizeCwd,
  projectGascitySessionToGhostex,
  reconcile as reconcileSessionState,
  type BridgedSession,
  type BridgeOptions,
  type BridgeResult,
  type BridgeVia,
  type CompletionSignal,
  type CorrelationKeyOptions,
  type FleetActivityOverlay,
  type GascityActivity,
  type GascityActivityInput,
  type GascityAgentLike,
  type GascityFleetLike,
  type GascityLifecycleInput,
  type GascityLiveness,
  type GascityOnlySession,
  type GascitySessionLike,
  type GascityToGhostexOptions,
  type ReconcilePolicy,
  type SessionStateSnapshot,
} from './stateSync.ts';
